name: ZMK Build

on:
  push:
    branches: [ main ]
  pull_request: {}

env:
  BASE_DIR: /tmp/zmk
  ZEPHYR_VERSION: v3.6.0
  CONTAINER_IMAGE: zmkfirmware/zmk-build-arm:stable

jobs:
  build:
    runs-on: docker
    container:
      image: ${CONTAINER_IMAGE}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare west workspace
        run: |
          mkdir -p ${BASE_DIR}
          cd ${BASE_DIR}
          west init -l "${GITHUB_WORKSPACE}"
          west update

      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            ${BASE_DIR}/modules
            ${BASE_DIR}/zephyr
            ${BASE_DIR}/zmk
          key: zephyr-modules-${ZEPHYR_VERSION}

      - name: Export Zephyr
        run: |
          cd ${BASE_DIR}
          west zephyr-export

      - name: Build Left (nice!nano v2)
        run: |
          cd ${BASE_DIR}
          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=corne_left

      - name: Build Right (nice!nano v2)
        run: |
          cd ${BASE_DIR}
          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=corne_right

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: |
            ${BASE_DIR}/build/zephyr/zmk.uf2
